### ISSUE TITLE
Unable to run this project

### ISSUE THREAD

**Issue by dkdevpro** [csieflyman/multi-projects-architecture-with-Ktor#1]
Hi, when i try to download and run the project it throws following error message.

`Exception in thread "main" java.lang.IllegalArgumentException: Neither port nor sslPort specified. Use command line options -port/-sslPort or configure connectors in application.conf`

**Comment by csieflyman** [comment]
I don't use ssl in this project. You can refer to [ktor official document](https://ktor.io/docs/server-ssl.html)
